####  PARAMETERS ####
parameters:
- name: ShouldBuildiOS
  displayName: Build iOS?
  type: boolean
  default: true

# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

jobs:
# Build iOS
- template: ./templates/build-ios.yml
  parameters:
    isEnabled: ${{ parameters.ShouldBuildiOS }}
